-- themeInfo = {
	-- ProductCode = "DDR_A3_ArcadeMod",
	-- Name = "DDR A3 (ArcadeMod)",
	-- Version = "4.0",
	-- Date = "20241207",
	-- Author = "KENP",
	-- Mod = "SchneiderAFX, Curilang, Inorizushi, Wyvern-D, Midflight Digital, Jindev, Lunah"
-- },
